<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Anvil' => $vendorDir . '/foonster/forge/Anvil.php',
    'Bullhorn' => $vendorDir . '/foonster/forge/ThirdParty/Bullhorn.php',
    'Calendar' => $vendorDir . '/foonster/forge/Calendar.php',
    'Database' => $vendorDir . '/foonster/forge/Database.php',
    'Email' => $vendorDir . '/foonster/forge/Email.php',
    'Foundation' => $vendorDir . '/foonster/forge/DisplayFrameworks/Foundation/Foundation.php',
    'Google' => $vendorDir . '/foonster/forge/ThirdParty/Google.php',
    'Html' => $vendorDir . '/foonster/forge/Html.php',
    'Image' => $vendorDir . '/foonster/forge/Image.php',
    'TWBootstrap' => $vendorDir . '/foonster/forge/DisplayFrameworks/TwitterBootstrap/TWBootstrap.php',
    'foonster\\ConstantContact' => $vendorDir . '/foonster/forge/ThirdParty/ConstantContact.php'
);
